In [ ]:
# Lab03 Numpy Basics

In [41]:
# NumPy Basics
import numpy as np

s = np.arange(12)
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
# 1) Show all element of s
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
# 2) Show the third element of s
print(s[2])

# 2) Show the last element of s
print(s[-1])

2
11


In [44]:
# 3) Show the third to last element of s
print(s[2:])

# Show the third to seventh element of s
print(s[2:7])

[ 2  3  4  5  6  7  8  9 10 11]
[2 3 4 5 6]


In [45]:

# 4) Show the total of s
print(np.sum(s))

# Show the smallest value of s
print(np.min(s))

# Show the average value of s
print(np.mean(s))

# Show the largest value of s
print(np.max(s))

66
0
5.5
11


In [46]:
# 5) if array change values, will s change values too? why?
# show s values
arry = s
arry[1]= -1
print(s)
print(arry)

[ 0 -1  2  3  4  5  6  7  8  9 10 11]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [47]:
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
print(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [48]:
matrix = np.array(data)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
# 6)Show the element of first row of second col of matrix
print(matrix[0,1])

# 6)Show the element of second row of first col of matrix
print(matrix[1,0])

2
4


In [53]:
# 7 )Show all elements of first row in matrix
print(matrix[0])

#  Show all elements of second row in matrix
print(matrix[1])

# Show all elements of last row in matrix
print(matrix[-1])

[1 2 3]
[4 5 6]
[7 8 9]


In [55]:
# 8) Show all elements of first col in matrix
print(matrix[:,0])

# Show all elements of third col in matrix
print(matrix[:,2])

# Show all elements of last col in matrix
print(matrix[:,-1])

[1 4 7]
[3 6 9]
[3 6 9]


In [58]:
print( matrix)
print('-----')
# Show second rows, and second col to last col's elements in matrix
print(matrix[1,1:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----
[5 6]


In [59]:
print(matrix)
# 5) Show the total of s

print(matrix.sum())
# Show the smallest value of s

print(matrix.min())

# Show the average value of s
print(matrix.mean())

# Show the largest value of s
print(matrix.max())

# The sum of second col
print(matrix[:,1].sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
1
5.0
9
15
